version: "3.8"

services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"

volumes:
  caddy_data:
  caddy_config:
  mongodb_data:
