version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - PORT=4000
